[tools]
act = "latest"
"aqua:caddyserver/caddy" = "latest"
bun = "latest"
dprint = "latest"
fnox = "latest"
go = "latest"
jless = "latest"
jnv = "latest"
lazydocker = "latest"
node = "24"
"npm:@biomejs/biome" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@moonrepo/cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:degit" = "latest"
"npm:eas-cli" = "16.32"
"npm:firecrawl-cli" = "latest"
"npm:firecrawl-mcp" = "latest"
"npm:mastracode" = "latest"
"npm:neovim" = "latest"
"npm:opencode-ai" = "latest"
"npm:quicktype" = "latest"
"npm:skills" = "latest"
"npm:turbo" = "latest"
"npm:typescript" = "latest"
"npm:wrangler" = "latest"
pnpm = "latest"
poetry = "latest"
python = "latest"
task = "latest"
usage = "latest"
uv = "latest"
